Repository GopeedLab/gopeed, pull requests merged in 2023-12, with the labels that each got.

#284 feat: support proxy
  CONTRIBUTING.md
  CONTRIBUTING_ja-JP.md
  CONTRIBUTING_zh-CN.md
  CONTRIBUTING_zh-TW.md
  README_zh-CN.md
  cmd/web/flags.go
  go.mod
  go.sum
  internal/controller/controller.go
  internal/protocol/bt/fetcher.go
  internal/protocol/bt/fetcher_test.go
  internal/protocol/http/fetcher.go
  internal/protocol/http/fetcher_test.go
  internal/test/httptest.go
  pkg/base/constants.go
  pkg/download/downloader.go
  pkg/download/downloader_test.go
  pkg/download/engine/engine.go
  pkg/download/engine/engine_test.go
  pkg/download/engine/inject/xhr/module.go
  pkg/download/extension.go
  pkg/download/model.go
  pkg/rest/server_test.go
  pkg/util/url.go
  ui/flutter/assets/locales/en_US.json
  ui/flutter/assets/locales/fa_IR.json
  ui/flutter/assets/locales/ja_JP.json
  ui/flutter/assets/locales/ru_RU.json
  ui/flutter/assets/locales/zh_CN.json
  ui/flutter/assets/locales/zh_TW.json
  ui/flutter/lib/api/model/downloader_config.dart
  ui/flutter/lib/api/model/downloader_config.g.dart
  ui/flutter/lib/app/modules/app/controllers/app_controller.dart
  ui/flutter/lib/app/modules/app/views/app_view.dart
  ui/flutter/lib/app/modules/extension/views/extension_view.dart
  ui/flutter/lib/app/modules/setting/views/setting_view.dart
  ui/flutter/lib/generated/locales.g.dart
  ui/flutter/lib/i18n/langs/en_us.dart
  ui/flutter/lib/i18n/langs/fa_ir.dart
  ui/flutter/lib/i18n/langs/ja_jp.dart
  ui/flutter/lib/i18n/langs/ru_ru.dart
  ui/flutter/lib/i18n/langs/zh_cn.dart
  ui/flutter/lib/i18n/langs/zh_tw.dart
  ui/flutter/lib/i18n/message.dart
  ui/flutter/lib/main.dart
Labels: enhancement

#285 fix: incorrect file name in task files view
  ui/flutter/lib/app/modules/task/views/task_files_view.dart
  ui/flutter/lib/app/views/buid_task_list_view.dart
Labels: bug

#297 fix: sort of completed tasks
  pkg/download/downloader.go
  pkg/download/model.go
  ui/flutter/lib/api/model/task.dart
  ui/flutter/lib/api/model/task.g.dart
  ui/flutter/lib/app/modules/task/controllers/task_downloaded_controller.dart
  ui/flutter/lib/app/modules/task/controllers/task_downloading_controller.dart
  ui/flutter/lib/app/modules/task/controllers/task_list_controller.dart
Labels: bug

#296 fix: repair invalid filename
  pkg/download/downloader.go
  pkg/download/extension.go
  pkg/util/path.go
  pkg/util/path_other.go
  pkg/util/path_test.go
  pkg/util/path_windows.go
Labels: bug

#298 feat: improve extension engine
  pkg/download/downloader.go
  pkg/download/engine/engine.go
  pkg/download/engine/engine_test.go
  pkg/download/engine/inject/error/module.go
  pkg/download/engine/inject/util.go
  pkg/download/engine/inject/xhr/module.go
  pkg/download/engine/util/util.go
  pkg/download/extension.go
  pkg/download/extension_test.go
  pkg/download/testdata/extensions/function_error/index.js
  pkg/download/testdata/extensions/message_error/index.js
  pkg/download/testdata/extensions/message_error/manifest.json
  pkg/download/testdata/extensions/on_error/index.js
  pkg/download/testdata/extensions/on_error/manifest.json
  pkg/download/testdata/extensions/on_start/index.js
  pkg/rest/server_test.go
Labels: enhancement

#291 feat: support volume storage directory on docker
  Dockerfile
  README.md
  README_ja-JP.md
  README_zh-CN.md
  README_zh-TW.md
  cmd/web/main.go
  docker-compose.yml
Labels: enhancement

#300 feat: improve zh-TW translation
  ui/flutter/lib/i18n/langs/zh_tw.dart
Labels: translation

#301 fix: adapt mobile proxy settings ui
  ui/flutter/lib/app/modules/setting/views/setting_view.dart
Labels: bug

#303 fix: http pause error
  internal/protocol/http/fetcher.go
Labels: bug

#302 fix: handle api panic
  pkg/download/downloader.go
  pkg/download/extension.go
  pkg/rest/server.go
Labels: bug
