Repository GopeedLab/gopeed, pull requests merged in 2023-02, with the labels that each got.

#70 init farsi languages
  ui/flutter/lib/i18n/langs/fa_ir.dart
  ui/flutter/lib/i18n/messages.dart
Labels: enhancement

#71 feat: reuse fetcher
  CONTRIBUTING.md
  CONTRIBUTING_zh-CN.md
  README.md
  README_zh-CN.md
  cmd/gopeed/main.go
  internal/fetcher/fetcher.go
  internal/protocol/bt/fetcher.go
  internal/protocol/bt/fetcher_test.go
  internal/protocol/http/fetcher.go
  internal/protocol/http/fetcher_test.go
  pkg/base/model.go
  pkg/download/downloader.go
  pkg/download/downloader_test.go
  pkg/download/model.go
  pkg/download/task.go
  pkg/rest/api.go
  pkg/rest/model/task.go
  pkg/rest/server_test.go
  pkg/util/path.go
  pkg/util/path_test.go
  ui/flutter/lib/api/api.dart
  ui/flutter/lib/api/model/create_task.dart
  ui/flutter/lib/api/model/create_task.g.dart
  ui/flutter/lib/api/model/downloader_config.dart
  ui/flutter/lib/api/model/downloader_config.g.dart
  ui/flutter/lib/api/model/meta.dart
  ui/flutter/lib/api/model/meta.g.dart
  ui/flutter/lib/api/model/request.dart
  ui/flutter/lib/api/model/resolve_result.dart
  ui/flutter/lib/api/model/resolve_result.g.dart
  ui/flutter/lib/api/model/resource.dart
  ui/flutter/lib/api/model/resource.g.dart
  ui/flutter/lib/api/model/task.dart
  ui/flutter/lib/api/model/task.g.dart
  ui/flutter/lib/pages/create/create_view.dart
  ui/flutter/lib/pages/task/task_view.dart
Labels: enhancement

#72 fix: windows version
  ui/flutter/.metadata
  ui/flutter/lib/pages/home/home_view.dart
  ui/flutter/pubspec.lock
  ui/flutter/pubspec.yaml
  ui/flutter/windows/runner/CMakeLists.txt
  ui/flutter/windows/runner/Runner.rc
  ui/flutter/windows/runner/flutter_window.cpp
  ui/flutter/windows/runner/main.cpp
  ui/flutter/windows/runner/runner.exe.manifest
  ui/flutter/windows/runner/win32_window.cpp
  ui/flutter/windows/runner/win32_window.h
Labels: bug

#73 feat: add cdn for tracker subscribe urls
  ui/flutter/lib/pages/app/app_controller.dart
Labels: enhancement

#74 ci: get last release include draft
  .github/ISSUE_TEMPLATE.md
  .github/workflows/build.yml
Labels: ci

#76 feat: auto rename on duplicate
  internal/fetcher/fetcher.go
  internal/protocol/bt/fetcher.go
  internal/protocol/bt/fetcher_test.go
  internal/protocol/http/fetcher.go
  pkg/base/model.go
  pkg/download/downloader.go
  pkg/util/path.go
  pkg/util/path_test.go
Labels: enhancement
