Repository GopeedLab/gopeed, pull requests merged in 2023-03, with the labels that each got.

#95 ci: flutter build check
  .github/workflows/test.yml
Labels: ci

#96 feat: api result add code
  pkg/rest/api.go
  pkg/rest/model/result.go
  pkg/rest/server.go
  pkg/rest/server_test.go
  pkg/rest/util/util.go
  ui/flutter/lib/api/api.dart
  ui/flutter/lib/api/model/result.dart
  ui/flutter/lib/api/model/result.g.dart
  ui/flutter/pubspec.lock
Labels: enhancement

#97 fix: crash caused by non-resumable http download resources
  internal/protocol/http/fetcher.go
  internal/protocol/http/fetcher_test.go
Labels: bug

#98 改正官方网站地址
  README_zh-CN.md
Labels: docs

#99 feat: smooth speed calculation
  pkg/download/downloader.go
  pkg/download/model.go
Labels: enhancement
