Repository GopeedLab/gopeed, pull requests merged in 2024-01, with the labels that each got.

#314 fix: foreground task scope
  ui/flutter/lib/app/modules/app/views/app_view.dart
  ui/flutter/lib/app/modules/home/views/home_view.dart
Labels: bug

#322 fix: compatible with not follow the http range response standard
  internal/protocol/http/fetcher.go
  pkg/base/constants.go
Labels: bug

#325 feat: add thanks item for contributors
  ui/flutter/lib/app/modules/setting/views/setting_view.dart
  ui/flutter/lib/i18n/langs/en_us.dart
  ui/flutter/lib/i18n/langs/fa_ir.dart
  ui/flutter/lib/i18n/langs/ja_jp.dart
  ui/flutter/lib/i18n/langs/ru_ru.dart
  ui/flutter/lib/i18n/langs/zh_cn.dart
  ui/flutter/lib/i18n/langs/zh_tw.dart
Labels: enhancement

#327 feat: improve zh-TW translation
  ui/flutter/lib/i18n/langs/zh_tw.dart
Labels: translation

#323 feat: add download stats info
  internal/fetcher/fetcher.go
  internal/protocol/bt/fetcher.go
  internal/protocol/http/fetcher.go
  pkg/protocol/bt/model.go
  pkg/protocol/http/model.go
Labels: enhancement

#330 feat: add mirror.ghproxy.com trackers subscribe cdn
  ui/flutter/lib/app/modules/app/controllers/app_controller.dart
Labels: enhancement

#328 fix: proxy setting only numeric input
  ui/flutter/lib/app/modules/setting/views/setting_view.dart
  ui/flutter/lib/i18n/langs/en_us.dart
  ui/flutter/lib/i18n/langs/zh_cn.dart
  ui/flutter/lib/i18n/langs/zh_tw.dart
Labels: bug

#329 ci: fix debian 12 depends
  .github/workflows/build.yml
  ui/flutter/linux/packaging/deb/make_config.yaml
  ui/flutter/linux/packaging/rpm/make_config.yaml
Labels: ci

#332 feat: save window size and resize on startup
  ui/flutter/lib/app/modules/app/controllers/app_controller.dart
  ui/flutter/lib/app/modules/create/views/create_view.dart
  ui/flutter/lib/main.dart
  ui/flutter/lib/util/util.dart
  ui/flutter/lib/util/window_util.dart
Labels: enhancement

#334 feat: auto create torrent task for http download
  pkg/download/downloader.go
  pkg/protocol/http/model.go
  ui/flutter/lib/api/model/options.dart
  ui/flutter/lib/api/model/options.g.dart
  ui/flutter/lib/app/modules/create/views/create_view.dart
Labels: enhancement

#337 fix: default download path on mobile
  ui/flutter/lib/app/modules/app/controllers/app_controller.dart
  ui/flutter/lib/app/views/directory_selector.dart
  ui/flutter/pubspec.lock
  ui/flutter/pubspec.yaml
Labels: bug

#338 feat: add batch delete tasks api
  pkg/download/downloader.go
  pkg/rest/api.go
  pkg/rest/server.go
  pkg/rest/server_test.go
Labels: enhancement

#339 feat: downloader task stats
  go.mod
  go.sum
  internal/protocol/http/fetcher.go
  pkg/download/downloader.go
  pkg/download/model.go
  pkg/rest/api.go
  pkg/rest/server.go
Labels: enhancement

#341 feat: custom torrent client version
  .github/workflows/build.yml
  .github/workflows/test.yml
  Dockerfile
  README.md
  README_ja-JP.md
  README_zh-CN.md
  README_zh-TW.md
  go.mod
  go.sum
  internal/protocol/bt/fetcher.go
  pkg/base/version.go
Labels: enhancement

#342 fix: missing pb size format
  pkg/util/bytefmt.go
Labels: bug

#343 feat: migrate shared_preferences to hive
  ui/flutter/.gitignore
  ui/flutter/lib/app/data/api_provider.dart
  ui/flutter/lib/app/modules/app/controllers/app_controller.dart
  ui/flutter/lib/app/modules/create/views/create_view.dart
  ui/flutter/lib/app/modules/history/controller/history_controller.dart
  ui/flutter/lib/app/modules/history/views/history_view.dart
  ui/flutter/lib/database/database.dart
  ui/flutter/lib/database/entity.dart
  ui/flutter/lib/database/entity.g.dart
  ui/flutter/lib/main.dart
  ui/flutter/lib/util/mac_secure_util.dart
  ui/flutter/lib/util/util.dart
  ui/flutter/lib/util/window_util.dart
  ui/flutter/pubspec.lock
  ui/flutter/pubspec.yaml
Labels: enhancement

#359 feat: support use server time for file creation
  .github/workflows/build.yml
  go.mod
  go.sum
  internal/protocol/http/config.go
  internal/protocol/http/fetcher.go
  internal/protocol/http/fetcher_test.go
  internal/test/httptest.go
  pkg/base/constants.go
  pkg/base/model.go
  pkg/download/downloader.go
  pkg/download/downloader_test.go
  pkg/rest/server_test.go
  ui/flutter/lib/api/model/downloader_config.dart
  ui/flutter/lib/api/model/downloader_config.g.dart
  ui/flutter/lib/app/modules/app/controllers/app_controller.dart
  ui/flutter/lib/app/modules/setting/views/setting_view.dart
  ui/flutter/lib/i18n/langs/en_us.dart
  ui/flutter/lib/i18n/langs/zh_cn.dart
  ui/flutter/lib/i18n/langs/zh_tw.dart
  ui/flutter/lib/main.dart
Labels: enhancement

#366 fix: windows default install dir
  .github/workflows/build.yml
Labels: bug
