Repository GopeedLab/gopeed, pull requests merged in 2024-09, with the labels that each got.

#660 fix: try request grant external storage on Android
  ui/flutter/android/app/src/main/AndroidManifest.xml
  ui/flutter/lib/app/views/directory_selector.dart
  ui/flutter/pubspec.lock
  ui/flutter/pubspec.yaml
Labels: bug

#719 feat: macos round icon
  ui/flutter/assets/icon/icon_macos_1024.png
  ui/flutter/macos/Podfile
  ui/flutter/macos/Podfile.lock
  ui/flutter/macos/Runner.xcodeproj/project.pbxproj
  ui/flutter/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  ui/flutter/macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_1024.png
  ui/flutter/macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_128.png
  ui/flutter/macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_16.png
  ui/flutter/macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_256.png
  ui/flutter/macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_32.png
  ui/flutter/macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_512.png
  ui/flutter/macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_64.png
Labels: enhancement

#727 feat: task separate proxy
  internal/controller/controller.go
  internal/protocol/bt/fetcher.go
  internal/protocol/bt/fetcher_test.go
  internal/protocol/http/fetcher.go
  internal/protocol/http/fetcher_test.go
  pkg/base/model.go
  pkg/download/downloader.go
  pkg/download/downloader_test.go
  pkg/download/engine/engine.go
  pkg/download/extension.go
  pkg/download/model.go
  pkg/util/json.go
  pkg/util/json_test.go
  ui/flutter/lib/api/model/request.dart
  ui/flutter/lib/api/model/request.g.dart
  ui/flutter/lib/api/model/resource.g.dart
  ui/flutter/lib/app/modules/create/controllers/create_controller.dart
  ui/flutter/lib/app/modules/create/views/create_view.dart
  ui/flutter/lib/app/modules/setting/views/setting_view.dart
  ui/flutter/lib/i18n/langs/en_us.dart
  ui/flutter/lib/i18n/langs/zh_cn.dart
  ui/flutter/lib/i18n/langs/zh_tw.dart
Labels: enhancement

#728 feat: support extension onDone event
  pkg/download/downloader.go
  pkg/download/extension.go
  pkg/download/extension_test.go
  pkg/download/testdata/extensions/on_done/index.js
  pkg/download/testdata/extensions/on_done/manifest.json
Labels: enhancement

#729 fix: avoid HTTP zero connections
  internal/protocol/http/fetcher.go
Labels: bug

#735 feat: support default direct download config
  ui/flutter/lib/api/model/downloader_config.dart
  ui/flutter/lib/api/model/downloader_config.g.dart
  ui/flutter/lib/app/modules/create/controllers/create_controller.dart
  ui/flutter/lib/app/modules/setting/views/setting_view.dart
  ui/flutter/lib/i18n/langs/en_us.dart
  ui/flutter/lib/i18n/langs/zh_cn.dart
  ui/flutter/lib/i18n/langs/zh_tw.dart
Labels: enhancement

#740 docs: improve banner image
  README.md
  README_ja-JP.md
  README_vi-VN.md
  README_zh-CN.md
  README_zh-TW.md
  _docs/img/banner.png
Labels: docs

#746 [ui][flutter] made dart analyser happy
  ui/flutter/lib/app/modules/create/views/create_view.dart
  ui/flutter/lib/app/modules/extension/views/extension_view.dart
  ui/flutter/lib/app/views/open_in_new.dart
Labels: enhancement

#750 fix: DotAll flag not working with group
  go.mod
  go.sum
Labels: bug

#737 fix: torrent stats panic
  internal/protocol/bt/fetcher.go
  ui/flutter/lib/app/modules/create/views/create_view.dart
  ui/flutter/lib/app/modules/extension/views/extension_view.dart
  ui/flutter/lib/app/views/open_in_new.dart
Labels: bug

#752 feat: support download directory white list
  pkg/base/error.go
  pkg/download/downloader.go
  pkg/download/downloader_test.go
  pkg/download/model.go
  pkg/rest/model/server.go
Labels: enhancement

#753 feat: supports batch operation of tasks by filter
  pkg/download/downloader.go
  pkg/download/downloader_test.go
  pkg/download/extension.go
  pkg/download/model.go
  pkg/rest/api.go
  pkg/rest/server.go
  pkg/rest/server_test.go
Labels: enhancement

#754 feat: Update tr_tr.dart
  ui/flutter/lib/i18n/langs/tr_tr.dart
Labels: translation
