Repository GopeedLab/gopeed, pull requests merged in 2024-08, with the labels that each got.

#625 fix: tray icon not shown on linux flatpak or snap
  ui/flutter/lib/app/modules/app/controllers/app_controller.dart
  ui/flutter/pubspec.lock
  ui/flutter/pubspec.yaml
Labels: bug

#629 feat: enhanced extension engine
  internal/protocol/http/fetcher.go
  pkg/download/engine/engine_test.go
  pkg/download/engine/inject/xhr/module.go
  pkg/download/engine/polyfill/out/index.js
  pkg/download/engine/polyfill/package-lock.json
  pkg/download/engine/polyfill/package.json
  pkg/download/engine/polyfill/patches/whatwg-fetch+3.6.20.patch
  pkg/download/engine/polyfill/src/index.js
Labels: enhancement

#630 feat(extension): get exception stacks on promise error
  go.mod
  go.sum
  pkg/download/engine/engine.go
  pkg/download/engine/inject/xhr/module.go
  pkg/download/extension.go
Labels: enhancement

#633 feat: task detail view
  .github/workflows/build.yml
  README.md
  README_ja-JP.md
  README_vi-VN.md
  README_zh-CN.md
  README_zh-TW.md
  ui/flutter/android/app/build.gradle
  ui/flutter/android/app/src/main/AndroidManifest.xml
  ui/flutter/lib/app/modules/app/controllers/app_controller.dart
  ui/flutter/lib/app/modules/setting/views/setting_view.dart
  ui/flutter/lib/app/modules/task/controllers/task_controller.dart
  ui/flutter/lib/app/modules/task/views/task_files_view.dart
  ui/flutter/lib/app/modules/task/views/task_view.dart
  ui/flutter/lib/app/views/buid_task_list_view.dart
  ui/flutter/lib/app/views/copy_button.dart
  ui/flutter/lib/i18n/langs/en_us.dart
  ui/flutter/lib/i18n/langs/zh_cn.dart
  ui/flutter/lib/i18n/langs/zh_tw.dart
  ui/flutter/lib/util/file_explorer.dart
  ui/flutter/lib/util/log_util.dart
  ui/flutter/pubspec.lock
  ui/flutter/pubspec.yaml
Labels: enhancement

#634 perf: excessive torrent tracker dns resolve
  .github/workflows/test.yml
  go.mod
  go.sum
  internal/protocol/bt/dns_cache_resolver.go
  internal/protocol/bt/fetcher.go
  pkg/download/downloader.go
  pkg/rest/api.go
Labels: perf

#635 fix: batch create tasks with duplicate names
  internal/test/httptest.go
  pkg/base/model.go
  pkg/download/downloader.go
  pkg/download/downloader_test.go
  pkg/rest/server.go
  pkg/rest/server_test.go
Labels: bug

#636 fix: web config file not loaded when is relative path
  cmd/server.go
  cmd/web/flags.go
  cmd/web/main.go
  pkg/base/model.go
  pkg/base/model_test.go
  pkg/rest/model/server.go
  ui/flutter/lib/app/modules/setting/views/setting_view.dart
Labels: bug

#637 ci: docker flutter build on host
  .dockerignore
  .github/release-drafter.yml
  .github/workflows/build.yml
  Dockerfile
  entrypoint.sh
Labels: ci

#642 fix: downgrade minSdkVersion
  ui/flutter/android/app/build.gradle
Labels: bug

#647 fix: task directory open
  ui/flutter/lib/app/modules/task/views/task_view.dart
Labels: bug

#648 fix: blocked when task paused while not ready
  pkg/download/downloader.go
Labels: bug

#649 fix: torrent redundant directory
  internal/fetcher/fetcher.go
  internal/protocol/bt/fetcher.go
  internal/protocol/bt/fetcher_test.go
  internal/protocol/bt/testdata/test.torrent
  internal/protocol/http/fetcher.go
  internal/protocol/http/fetcher_test.go
  pkg/download/downloader.go
  pkg/download/model.go
  ui/flutter/lib/api/model/downloader_config.g.dart
  ui/flutter/lib/api/model/task.dart
  ui/flutter/lib/api/model/task.g.dart
  ui/flutter/lib/app/modules/task/views/task_view.dart
  ui/flutter/lib/app/views/buid_task_list_view.dart
Labels: bug

#667 feat: Add spanish language
  ui/flutter/lib/i18n/langs/es_es.dart
  ui/flutter/lib/i18n/message.dart
Labels: translation
