Repository GopeedLab/gopeed, pull requests merged in 2024-03, with the labels that each got.

#398 feat: docker download dir move to /app/Download
  .github/workflows/build.yml
  Dockerfile
  cmd/server.go
  pkg/base/info.go
Labels: enhancement

#402 feat: Create tr_tr.dart
  ui/flutter/lib/i18n/langs/tr_tr.dart
  ui/flutter/lib/i18n/message.dart
Labels: translation

#419 feat: Support Via Download task, require via version 5.5.0 or above (#412)
  ui/flutter/android/app/src/main/AndroidManifest.xml
  ui/flutter/lib/app/modules/app/controllers/app_controller.dart
Labels: enhancement

#428 feat: web config add stroage dir
  cmd/web/flags.go
  cmd/web/main.go
Labels: enhancement

#431 fix: task lock by unreachable torrent
  internal/protocol/bt/fetcher.go
  pkg/download/downloader.go
  pkg/download/model.go
  ui/flutter/lib/api/model/options.dart
  ui/flutter/lib/api/model/options.g.dart
Labels: bug

#433 feat: add browser extension link
  ui/flutter/lib/app/modules/setting/views/setting_view.dart
  ui/flutter/lib/app/views/open_in_new.dart
  ui/flutter/lib/i18n/langs/en_us.dart
  ui/flutter/lib/i18n/langs/fa_ir.dart
  ui/flutter/lib/i18n/langs/ja_jp.dart
  ui/flutter/lib/i18n/langs/ru_ru.dart
  ui/flutter/lib/i18n/langs/tr_tr.dart
  ui/flutter/lib/i18n/langs/vi_vn.dart
  ui/flutter/lib/i18n/langs/zh_cn.dart
  ui/flutter/lib/i18n/langs/zh_tw.dart
Labels: enhancement

#434 fix: entrypoint_sh
  entrypoint.sh
Labels: bug
