Repository GopeedLab/gopeed, pull requests merged in 2024-10, with the labels that each got.

#777 feat: Updated the indonesian translation
  README_vi-VN.md
  ui/flutter/lib/i18n/langs/id_id.dart
Labels: translation

#785 ci: fix windows build version
  .github/workflows/build.yml
Labels: ci

#791 feat: upgrade flutter to v3.24.3
  .github/workflows/build.yml
  .github/workflows/test.yml
  README.md
  README_ja-JP.md
  README_vi-VN.md
  README_zh-CN.md
  README_zh-TW.md
  ui/flutter/lib/app/modules/app/controllers/app_controller.dart
  ui/flutter/macos/Podfile.lock
  ui/flutter/macos/Runner.xcodeproj/project.pbxproj
  ui/flutter/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  ui/flutter/macos/Runner/AppDelegate.swift
  ui/flutter/pubspec.lock
  ui/flutter/pubspec.yaml
Labels: enhancement

#787 fix: avoid request locatoin permisson on windows
  ui/flutter/pubspec.lock
  ui/flutter/pubspec.yaml
Labels: bug
