Repository GopeedLab/gopeed, pull requests merged in 2024-05, with the labels that each got.

#512 feat: updated iOS icons
  ui/flutter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png
  ui/flutter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png
  ui/flutter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png
  ui/flutter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png
  ui/flutter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png
  ui/flutter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png
  ui/flutter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png
  ui/flutter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png
  ui/flutter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png
  ui/flutter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png
  ui/flutter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-50x50@1x.png
  ui/flutter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-50x50@2x.png
  ui/flutter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-57x57@1x.png
  ui/flutter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-57x57@2x.png
  ui/flutter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png
  ui/flutter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png
  ui/flutter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-72x72@1x.png
  ui/flutter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-72x72@2x.png
  ui/flutter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png
  ui/flutter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png
  ui/flutter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png
Labels: enhancement

#514 fix: http request cookie incremented indefinitely on retries
  internal/protocol/http/fetcher.go
Labels: bug

#515 feat: support system proxy
  go.mod
  go.sum
  internal/controller/controller.go
  internal/protocol/bt/fetcher.go
  internal/protocol/bt/fetcher_test.go
  internal/protocol/http/fetcher.go
  internal/protocol/http/fetcher_test.go
  internal/test/httptest.go
  pkg/base/model.go
  pkg/download/downloader.go
  pkg/download/downloader_test.go
  pkg/download/engine/engine.go
  pkg/download/engine/engine_test.go
  pkg/download/engine/inject/xhr/module.go
  pkg/download/extension.go
  pkg/download/model.go
  pkg/rest/api.go
  pkg/rest/server_test.go
  pkg/util/url.go
  ui/flutter/lib/api/model/downloader_config.dart
  ui/flutter/lib/api/model/downloader_config.g.dart
  ui/flutter/lib/api/model/options.g.dart
  ui/flutter/lib/api/model/resource.g.dart
  ui/flutter/lib/api/model/result.g.dart
  ui/flutter/lib/api/model/task.g.dart
  ui/flutter/lib/app/modules/setting/views/setting_view.dart
  ui/flutter/lib/core/common/start_config.g.dart
  ui/flutter/lib/i18n/langs/en_us.dart
  ui/flutter/lib/i18n/langs/zh_cn.dart
  ui/flutter/lib/i18n/langs/zh_tw.dart
Labels: enhancement

#516 feat: support double click to open task file
  ui/flutter/lib/app/modules/task/views/task_files_view.dart
  ui/flutter/lib/app/views/buid_task_list_view.dart
Labels: enhancement

#520 feat: add extension store links for edge and firefox
  ui/flutter/lib/app/modules/setting/views/setting_view.dart
Labels: enhancement

#524 feat: check API port is in use
  ui/flutter/lib/app/modules/app/controllers/app_controller.dart
  ui/flutter/lib/app/modules/setting/views/setting_view.dart
  ui/flutter/lib/i18n/langs/en_us.dart
  ui/flutter/lib/i18n/langs/zh_cn.dart
  ui/flutter/lib/i18n/langs/zh_tw.dart
Labels: enhancement

#532 feat: support launch at startup
  ui/flutter/lib/app/modules/app/controllers/app_controller.dart
  ui/flutter/lib/app/modules/setting/views/setting_view.dart
  ui/flutter/lib/i18n/langs/en_us.dart
  ui/flutter/lib/i18n/langs/zh_cn.dart
  ui/flutter/lib/i18n/langs/zh_tw.dart
  ui/flutter/lib/main.dart
  ui/flutter/lib/util/util.dart
  ui/flutter/linux/my_application.cc
  ui/flutter/macos/Runner/MainFlutterWindow.swift
  ui/flutter/pubspec.lock
  ui/flutter/pubspec.yaml
  ui/flutter/windows/runner/flutter_window.cpp
Labels: enhancement

#534 feat: add Polish translation
  ui/flutter/lib/i18n/langs/pl_pl.dart
  ui/flutter/lib/i18n/message.dart
Labels: translation

#535 fix: bt request extra type convert
  internal/protocol/bt/fetcher.go
Labels: bug

#540 feat: add batch create and server info APIs
  pkg/download/downloader.go
  pkg/download/downloader_test.go
  pkg/download/storage.go
  pkg/rest/api.go
  pkg/rest/model/action.go
  pkg/rest/model/task.go
  pkg/rest/server.go
  pkg/rest/server_test.go
Labels: enhancement

#541 feat: improve Android download directory choose
  ui/flutter/lib/app/modules/app/controllers/app_controller.dart
  ui/flutter/lib/app/modules/setting/views/setting_view.dart
  ui/flutter/lib/app/views/directory_selector.dart
  ui/flutter/pubspec.lock
  ui/flutter/pubspec.yaml
Labels: enhancement

#542 feat: remember delete task option
  ui/flutter/lib/api/model/downloader_config.dart
  ui/flutter/lib/api/model/downloader_config.g.dart
  ui/flutter/lib/api/model/options.g.dart
  ui/flutter/lib/api/model/resource.g.dart
  ui/flutter/lib/api/model/result.g.dart
  ui/flutter/lib/api/model/task.g.dart
  ui/flutter/lib/app/modules/app/controllers/app_controller.dart
  ui/flutter/lib/app/modules/create/views/create_view.dart
  ui/flutter/lib/app/views/buid_task_list_view.dart
  ui/flutter/lib/app/views/compact_checkbox.dart
  ui/flutter/lib/core/common/start_config.g.dart
Labels: enhancement

#554 feat: Update pl_pl.dart
  ui/flutter/lib/i18n/langs/pl_pl.dart
Labels: translation

#563 feat :tamil translation is added and updated CONTRIBUTING.md
  CONTRIBUTING.md
  ui/flutter/lib/app/modules/create/views/create_view.dart
  ui/flutter/lib/i18n/langs/ta_ta.dart
  ui/flutter/lib/i18n/message.dart
Labels: translation
