Repository GopeedLab/gopeed, pull requests merged in 2024-04, with the labels that each got.

#445 feat: Update tr_tr.dart
  ui/flutter/lib/i18n/langs/tr_tr.dart
Labels: translation

#449 fix: Fix the issue of installing apk files(Android) (#448)
  ui/flutter/android/app/src/main/AndroidManifest.xml
Labels: bug

#465 docs: fix Linux download links
  README.md
Labels: docs

#501 build linux with ubuntu latest
  .github/workflows/build.yml
Labels: ci

#508 ci: build gopeed with libayatana-appindicator
  .github/workflows/build.yml
  ui/flutter/linux/packaging/deb/make_config.yaml
  ui/flutter/linux/packaging/rpm/make_config.yaml
Labels: ci
