Repository GopeedLab/gopeed, pull requests merged in 2024-11, with the labels that each got.

#798 fix: download path in docker-compose.yml
  docker-compose.yml
Labels: bug

#801 feat(http): add option to skip SSL certificate verification
  internal/protocol/http/fetcher.go
  pkg/base/model.go
  ui/flutter/lib/api/model/request.dart
  ui/flutter/lib/api/model/request.g.dart
  ui/flutter/lib/app/modules/create/views/create_view.dart
  ui/flutter/lib/i18n/langs/en_us.dart
  ui/flutter/lib/i18n/langs/es_es.dart
  ui/flutter/lib/i18n/langs/fa_ir.dart
  ui/flutter/lib/i18n/langs/fr_fr.dart
  ui/flutter/lib/i18n/langs/id_id.dart
  ui/flutter/lib/i18n/langs/it_it.dart
  ui/flutter/lib/i18n/langs/ja_jp.dart
  ui/flutter/lib/i18n/langs/pl_pl.dart
  ui/flutter/lib/i18n/langs/ru_ru.dart
  ui/flutter/lib/i18n/langs/ta_ta.dart
  ui/flutter/lib/i18n/langs/tr_tr.dart
  ui/flutter/lib/i18n/langs/vi_vn.dart
  ui/flutter/lib/i18n/langs/zh_cn.dart
  ui/flutter/lib/i18n/langs/zh_tw.dart
Labels: enhancement

#808 fix: proxy config reload panic
  pkg/base/model.go
Labels: bug

#813 fix: android build on go 1.23
  .github/workflows/build.yml
  go.mod
  go.sum
  internal/protocol/bt/file.go
Labels: bug

#812 ci: add build tests for all platforms
  .github/workflows/test.yml
Labels: ci

#821 fix: revert flutter version to v3.16.8
  .github/workflows/build.yml
  .github/workflows/test.yml
  README.md
  README_ja-JP.md
  README_vi-VN.md
  README_zh-CN.md
  README_zh-TW.md
  ui/flutter/lib/app/modules/app/controllers/app_controller.dart
  ui/flutter/macos/Podfile.lock
  ui/flutter/macos/Runner.xcodeproj/project.pbxproj
  ui/flutter/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  ui/flutter/macos/Runner/AppDelegate.swift
  ui/flutter/pubspec.lock
  ui/flutter/pubspec.yaml
Labels: bug

#827 feat: optimize docker build
  Dockerfile
  docker-compose.yml
Labels: enhancement

#828 feat: add QNAP platform build
  .github/workflows/build.yml
Labels: enhancement
