Repository GopeedLab/gopeed, pull requests merged in 2024-07, with the labels that each got.

#593 feat: update tr_tr.dart
  ui/flutter/lib/i18n/langs/tr_tr.dart
Labels: translation

#596 fix: xhr string request body can specify Content-Type
  pkg/download/engine/inject/xhr/module.go
Labels: bug

#606 feat: Indonesian Translation/Localization
  ui/flutter/lib/i18n/langs/id_id.dart
  ui/flutter/lib/i18n/message.dart
Labels: translation

#608 feat: create fr_fr.dart
  ui/flutter/lib/i18n/langs/fr_fr.dart
Labels: translation

#611 feat: Update Traditional Chinese translation
  ui/flutter/lib/i18n/langs/zh_tw.dart
Labels: translation

#620 fix: handle empty string params
  README.md
  README_ja-JP.md
  README_vi-VN.md
  README_zh-CN.md
  README_zh-TW.md
  internal/protocol/http/fetcher.go
  ui/flutter/lib/app/modules/create/views/create_view.dart
Labels: bug

#599 feat: torrent seed config
  internal/controller/controller.go
  internal/fetcher/fetcher.go
  internal/protocol/bt/config.go
  internal/protocol/bt/fetcher.go
  internal/protocol/bt/fetcher_test.go
  internal/protocol/http/fetcher.go
  internal/protocol/http/fetcher_test.go
  pkg/base/model.go
  pkg/download/downloader.go
  pkg/download/downloader_test.go
  pkg/download/extension_test.go
  pkg/download/model.go
  pkg/download/testdata/extensions/on_error/index.js
  pkg/protocol/bt/model.go
  ui/flutter/lib/api/model/downloader_config.dart
  ui/flutter/lib/api/model/downloader_config.g.dart
  ui/flutter/lib/api/model/task.dart
  ui/flutter/lib/api/model/task.g.dart
  ui/flutter/lib/app/modules/setting/views/setting_view.dart
  ui/flutter/lib/i18n/langs/en_us.dart
  ui/flutter/lib/i18n/langs/zh_cn.dart
  ui/flutter/lib/i18n/langs/zh_tw.dart
Labels: enhancement
