Repository GopeedLab/gopeed, pull requests merged in 2025-02, with the labels that each got.

#895 fix: firefox native host integration
  ui/flutter/lib/util/browser_extension_host/entry/browser_extension_host_native.dart
Labels: bug

#901 fix: advanced options used by default when creating task
  ui/flutter/lib/app/modules/create/views/create_view.dart
Labels: bug

#903 feat: support tcp protocol on android
  ui/flutter/lib/app/modules/setting/views/setting_view.dart
Labels: enhancement

#902 feat: update android target sdk to 34
  ui/flutter/android/app/build.gradle
  ui/flutter/android/app/src/main/AndroidManifest.xml
  ui/flutter/lib/main.dart
Labels: enhancement

#908 fix: web white screen
  ui/flutter/lib/main.dart
Labels: bug

#909 feat: add ukraine language
  ui/flutter/lib/i18n/langs/uk_ua.dart
  ui/flutter/lib/i18n/message.dart
Labels: translation

#913 docs: improve download links
  .github/release-drafter.yml
  README.md
  README_ja-JP.md
  README_vi-VN.md
  README_zh-CN.md
  README_zh-TW.md
Labels: docs

#917 feat: improve Turkish Locales
  ui/flutter/lib/i18n/langs/tr_tr.dart
Labels: translation

#935 ci: add linux arm64 build
  .github/workflows/build.yml
  .github/workflows/test.yml
Labels: ci

#936 fix: windows title bar theme switch
  ui/flutter/lib/app/modules/app/views/app_view.dart
Labels: bug

#939 fix: path url encode filename parse
  internal/protocol/http/fetcher.go
  internal/protocol/http/fetcher_test.go
  internal/test/httptest.go
Labels: bug

#945 fix: can not open url encode torrent file path
  ui/flutter/lib/app/modules/app/controllers/app_controller.dart
Labels: bug
