Repository GopeedLab/gopeed, pull requests merged in 2025-03, with the labels that each got.

#951 feat: improve http download retry strategy
  internal/protocol/http/fetcher.go
Labels: enhancement

#940 feat: Add Hungarian languages
  ui/flutter/lib/i18n/langs/hu_hu
Labels: translation

#933 feat: auto updater
  .github/release-drafter.yml
  .github/workflows/build.yml
  README.md
  README_ja-JP.md
  README_vi-VN.md
  README_zh-CN.md
  README_zh-TW.md
  cmd/host/main.go
  cmd/updater/main.go
  cmd/updater/updater_darwin.go
  cmd/updater/updater_linux.go
  cmd/updater/updater_windows.go
  ui/flutter/.gitignore
  ui/flutter/assets/exec/.gitkeep
  ui/flutter/lib/app/modules/app/controllers/app_controller.dart
  ui/flutter/lib/app/modules/setting/controllers/setting_controller.dart
  ui/flutter/lib/app/modules/setting/views/setting_view.dart
  ui/flutter/lib/i18n/langs/hu_hu.dart
  ui/flutter/lib/i18n/message.dart
  ui/flutter/lib/main.dart
  ui/flutter/lib/util/arch/arch.dart
  ui/flutter/lib/util/arch/arch_stub.dart
  ui/flutter/lib/util/arch/entry/arch_native.dart
  ui/flutter/lib/util/arch/entry/arch_web.dart
  ui/flutter/lib/util/browser_extension_host/entry/browser_extension_host_native.dart
  ui/flutter/lib/util/github_mirror.dart
  ui/flutter/lib/util/updater.dart
  ui/flutter/lib/util/util.dart
  ui/flutter/pubspec.lock
  ui/flutter/pubspec.yaml
Labels: enhancement

#961 feat: web http file server caching and gzip support
  .github/workflows/build.yml
  pkg/rest/gizp_middleware.go
  pkg/rest/server.go
  pkg/rest/server_test.go
Labels: enhancement

#960 fix: web auth priority when api token and basic auth coexist
  pkg/rest/server.go
  pkg/rest/server_test.go
Labels: bug

#959 fix: http download size exceeds file size
  .github/workflows/test.yml
  internal/protocol/http/fetcher.go
  internal/protocol/http/fetcher_test.go
  internal/test/httptest.go
  pkg/download/downloader.go
  pkg/download/model.go
Labels: bug

#962 ci: apk build split abi
  .github/release-drafter.yml
  .github/workflows/build.yml
  README.md
  README_ja-JP.md
  README_vi-VN.md
  README_zh-CN.md
  README_zh-TW.md
Labels: ci
