Repository GopeedLab/gopeed, pull requests merged in 2025-08, with the labels that each got.

#1084 add german language support
  ui/flutter/lib/i18n/langs/de_de.dart
  ui/flutter/lib/i18n/message.dart
Labels: translation

#1086 ci: update macOS version to macos-14
  .github/workflows/build.yml
  .github/workflows/test.yml
Labels: ci

#1088 feat: add environment variables configuration support
  .github/workflows/test.yml
  cmd/web/flags.go
  cmd/web/flags_test.go
  cmd/web/main.go
  pkg/download/downloader.go
  pkg/download/downloader_test.go
  pkg/download/model.go
  pkg/rest/server.go
Labels: enhancement

#1087 feat: update storage directory path for Windows
  ui/flutter/lib/util/util.dart
Labels: enhancement
