Repository GopeedLab/gopeed, pull requests merged in 2025-04, with the labels that each got.

#969 feat: improve http download strategy to prevent speed drops near completion
  internal/protocol/http/fetcher.go
  internal/protocol/http/fetcher_test.go
  pkg/download/downloader.go
  pkg/protocol/http/model.go
Labels: enhancement

#975 fix: resolve http non encode attachment filename
  internal/controller/controller.go
  internal/protocol/http/fetcher.go
  internal/protocol/http/fetcher_test.go
  internal/test/httptest.go
Labels: bug

#978 feat: use batch download api for create multitasks
  pkg/base/model.go
  pkg/download/downloader.go
  pkg/download/downloader_test.go
  pkg/rest/api.go
  pkg/rest/model/task.go
  pkg/rest/server_test.go
  ui/flutter/lib/api/api.dart
  ui/flutter/lib/api/model/create_task_batch.dart
  ui/flutter/lib/api/model/create_task_batch.g.dart
  ui/flutter/lib/app/modules/create/views/create_view.dart
Labels: enhancement

#982 feat: update ru_ru.dart
  ui/flutter/lib/i18n/langs/ru_ru.dart
Labels: translation

#985 fix: bt seed cause crash
  internal/protocol/bt/fetcher.go
Labels: bug

#967 ci: build separate macos packages
  .github/release-drafter.yml
  .github/workflows/build.yml
  README.md
  README_ja-JP.md
  README_vi-VN.md
  README_zh-CN.md
  README_zh-TW.md
  ui/flutter/lib/util/updater.dart
Labels: ci

#986 ci: workaround for app_indicator_new is deprecated
  ui/flutter/linux/CMakeLists.txt
Labels: ci

#1014 fix: json syntax error in bt config
  internal/protocol/bt/config.go
Labels: bug

#1011 fix: do not add external tracker to a private torrent
  internal/protocol/bt/fetcher.go
Labels: enhancement
